#!/bin/bash

DEMOCA="demoCA";

if  [ -d $DEMOCA ]; then
	echo "$DEMOCA exists, remove first before setup";
else 
	echo "$DEMOCA does not exist, creating";
	mkdir $DEMOCA
	mkdir $DEMOCA/certs
	mkdir $DEMOCA/crl
	touch $DEMOCA/index.txt
	mkdir $DEMOCA/newcerts
	mkdir $DEMOCA/requests
	echo "1000" > $DEMOCA/serial
	mkdir $DEMOCA/private

	# WHAT DOES THIS DO?
	openssl genrsa -des3 -out $DEMOCA/private/cakey.pem 1024
	# Generates a new private rsa key using the triple DES cipher where the size of the key is 1024 (in bits).
	# This prompts for a password, and saves the key to $DEMOCA/private/cakey.pem

	openssl req -config openssl.conf -new -x509 -days 1001 -key $DEMOCA/private/cakey.pem -out $DEMOCA/cacert.pem
	# Use the previously generated private key to create a self-signed certificate. The -x509 makes makes it self-signed.
	# It is not a root certificate since, in the openssl.conf file:
	# basicConstraints=CA:FALSE
	# since this is not marked as critical 


	# Look in the $DEMOCA directories and document the files that were created
	# The above does ...
	# The following files will be created in $DEMOCA
	# $DEMOCA/private/cakey.pem
	# 	YOUR DESCRIPTION OF THIS FILE BELOW, WHAT DOES IT CONTAIN, WHAT IS ITS ROLE IN THIS GAME
	#	This is the private rsa key generated in the first openssl call. It is encrypted, and the header specifies the encryption type:
	# 	DEK-Info: DES-EDE3-CBC,A4FA0CB0826B9978
	#	So the key uses 3DES in EDE mode with cipher block chaining
	# 	...
	# $DEMOCA/cacert.pem
	# 	YOUR DESCRIPTION OF THIS FILE BELOW, WHAT DOES IT CONTAIN, WHAT IS ITS ROLE IN THIS GAME
	#	This is the encrypted certificate. The contents are entirely encrypted (unlike private/cakey.pem which also contained a header).
	#	The content can be decrypted using:
	# 	openssl x509 -in cacert.pem -inform pem -text -noout
	#	Once decrypted, we see that the certificate is self-signed certificate. 
	# 	...
	# $DEMOCA/index.txt
	#	This is the database, starts empty
	# DEMOCA/serial
	#	Is used to assign unique IDs to each certificate. The next certificate serial number is stored here.
	#

	openssl x509 -in $DEMOCA/cacert.pem -noout -text
	# DOCUMENT ITS OUTPUT, DESCRIBE THE IMPORTANT PARTS OF YOUR x509 certificate
	# Certificate:
	# Notice that the Issuer and the subject are identical.
	# "x509v3 Basic constraints: CA:TRUE" tells us that this is a certificate authority.
:'    Data:
        Version: 3 (0x2)
        Serial Number:
            e0:67:21:95:e7:c2:57:aa
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = AU, ST = Some-State, O = Internet Widgits Pty Ltd
        Validity
            Not Before: Nov 15 00:09:03 2017 GMT
            Not After : Aug 12 00:09:03 2020 GMT
        Subject: C = AU, ST = Some-State, O = Internet Widgits Pty Ltd
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (1024 bit)
                Modulus:
                    00:e2:a5:a7:b4:ad:75:43:c6:4a:68:06:e6:2e:34:
                    6e:0a:c1:d5:fe:c3:78:54:09:ec:fc:c2:46:b4:58:
                    e0:fd:e7:78:b9:48:e7:ed:aa:0c:29:67:5f:a0:bc:
                    ef:1c:8b:db:a7:0e:37:54:c6:2b:70:e5:9c:b3:2c:
                    31:ba:43:13:e6:15:2f:20:04:ca:35:5c:58:34:50:
                    17:5f:ae:ae:32:a8:5c:16:50:68:56:07:f7:c8:8d:
                    9e:92:fe:f3:95:d8:3a:e8:84:11:c6:38:0d:d0:bd:
                    c0:13:17:9c:03:7c:37:fa:64:a0:3f:ab:44:8e:ba:
                    26:30:40:24:75:b7:f2:97:a1
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                08:81:34:3A:10:5E:1A:BD:B4:37:4B:61:9E:4B:4D:94:54:EA:57:97
            X509v3 Authority Key Identifier: 
                keyid:08:81:34:3A:10:5E:1A:BD:B4:37:4B:61:9E:4B:4D:94:54:EA:57:97
                DirName:/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd
                serial:E0:67:21:95:E7:C2:57:AA

            X509v3 Basic Constraints: 
                CA:TRUE
    Signature Algorithm: sha256WithRSAEncryption
         9d:84:67:04:1a:dd:c1:3d:8e:3e:fb:dc:22:1e:1c:bb:55:4c:
         a0:55:9e:78:63:a6:8f:96:97:7e:d1:3b:24:8e:e0:73:19:ee:
         f7:fc:52:1f:ce:df:d5:8d:d3:be:28:3a:37:27:4f:bb:32:ab:
         1d:18:c1:07:a7:6a:1d:9c:fe:23:1f:eb:ee:c8:f3:1f:76:c2:
         af:5e:45:e4:ad:f6:86:ca:56:0a:9c:84:37:75:93:53:63:bf:
         29:1e:9e:fe:df:de:82:7a:6a:34:92:39:2f:e4:a7:7c:72:37:
         e1:ec:c7:c0:30:62:4d:38:ed:52:52:c3:f6:7c:4a:8a:3a:d8:
         6a:b5

'	
fi

